# Global options
[mypy]
python_version = 3.10
files = mongo_queries_manager
mypy_path = MongoDBQueriesManager
namespace_packages = True
explicit_package_bases = True
show_error_codes = True
strict = True
ignore_missing_imports = False
strict_optional = True
enable_error_code = ignore-without-code, redundant-expr, truthy-bool
