name: Main workflow

on:
  push:
    paths-ignore:
      - 'examples/**'
    branches:
      - main
      - develop
  pull_request:
    paths-ignore:
      - 'examples/**'
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: Tests on Python ${{ matrix.python }}  🐍
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Setup up workflow test directory
        run: mkdir ./reports

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.12"

      - name: Install dev dependencies
        run: |
          uv sync --locked --all-groups --dev

      - name: Run mypy
        run: uv run mypy mongo_queries_manager
        if: ${{ always() }}

      - name: Run ruff check
        run: uv run ruff check mongo_queries_manager
        if: ${{ always() }}

      - name: Run ruff format
        run: uv run ruff format --check mongo_queries_manager
        if: ${{ always() }}

      - name: Run Pytest without extra
        run: uv run coverage run --data-file=./reports/.coverage.without.extra -m pytest --junitxml=./reports/junit-results-without-extra-${{ matrix.python }}.xml --junit-prefix=without-extra-${{ matrix.python }} -vv
        if: ${{ always() }}

      - name: Archive Pytest artifact
        uses: actions/upload-artifact@v6
        with:
          name: junit-results-without-extra-${{ matrix.python }}
          path: ./reports/junit-results-without-extra-${{ matrix.python }}.xml

      - name: Install dateparser dependencies
        run: |
          uv sync --locked --all-extras --all-groups --dev

      - name: Run Pytest with extra
        run: uv run coverage run --data-file=./reports/.coverage.with.extra -m pytest --junitxml=./reports/junit-results-with-extra-${{ matrix.python }}.xml --junit-prefix=with-extra-${{ matrix.python }} -vv
        if: ${{ always() }}

      - name: Archive Pytest artifact
        uses: actions/upload-artifact@v6
        with:
          name: junit-results-with-extra-${{ matrix.python }}
          path: ./reports/junit-results-with-extra-${{ matrix.python }}.xml

      - name: Combine coverage
        run: uv run coverage combine --append --data-file=./reports/.coverage.full ./reports/.coverage.without.extra ./reports/.coverage.with.extra

      - name: Generate coverage HTML
        run: uv run coverage html --data-file=./reports/.coverage.full --directory=./reports/${{ matrix.python }}-coverage-full-html

      - name: Tar files
        run: tar -cvf ${{ matrix.python }}-coverage-full-html.tar ./reports/${{ matrix.python }}-coverage-full-html

      - name: Archive code coverage HTML results
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.python }}-coverage-full-html
          path: ${{ matrix.python }}-coverage-full-html.tar

      - name: Generate coverage XML
        run: uv run coverage xml --data-file=./reports/.coverage.full -o ./reports/coverage-${{ matrix.python }}-full.xml

      - name: Archive code coverage XML results
        uses: actions/upload-artifact@v6
        with:
          name: coverage-${{ matrix.python }}-full
          path: ./reports/coverage-${{ matrix.python }}-full.xml

      - name: Send code coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./reports
          files: coverage-${{ matrix.python }}-full.xml
          flags: pytests
          fail_ci_if_error: true
          verbose: true
